run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - gosec
    - ineffassign
    - misspell
    - unconvert
    - gocritic
    - gocyclo
    - gocognit
    - revive
    - staticcheck
    - typecheck
    - unused
    - shadow

  disable:
    - errcheck
    - gosimple
    - structcheck
    - varcheck
    - deadcode
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

issues:
  exclude-dirs:
    - vendor
    - testdata
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
    - linters:
        - lll
      source: "^//go:generate "
